# -*- coding: utf-8 -*-
"""Untitled35.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1uyCOJfZAA7atWZTQaM472FPqDoPcxqHo
"""

from google.colab import drive
drive.mount('/content/drive')

!pip install torch==1.8.1 torchvision==0.9.1

# Commented out IPython magic to ensure Python compatibility.
!git clone https://github.com/ultralytics/yolov5  # clone
# %cd yolov5
# %pip install -qr requirements.txt  # install

import torch
import utils
display = utils.notebook_init()  # checks

# Commented out IPython magic to ensure Python compatibility.
# %pip install -q wandb
import wandb
wandb.login()

# Commented out IPython magic to ensure Python compatibility.
# %load_ext tensorboard
# %tensorboard --logdir runs/train

!python train.py --img 1280 --batch 12 --epochs 30 --data custom.yaml --weights yolov5s.pt --cache